graph TD
    A[Composición Química de Materiales] --> B(Rocas y Minerales);
    A --> C(Arcillas);
    A --> D(Madera);
    E[Reacciones Químicas] --> F(Carbonatación);
    E --> G(Calcinación);
    E --> H(Hidratación);
    E --> I(Redox);
    J[Disolución y Solubilidad] --> K(Carbonato Cálcico);
    L[Procesos Físico-Químicos] --> M(Meteorización);
    L --> N(Gelifracción);
    L --> O(Higroscopicidad);
    L --> P(Sinterización);
    Q[Aglomerantes y Pigmentos]
    R[Estructura Cristalina]
    S[Basicidad]
    T[Humedad]